version: '3.0'

services:
  node:
    build: .
    # image: oaw/wcagemtool        
    command: npm start
    restart: always
    container_name: wcag_em_tool_node

  nginx:
    image: nginx:1.13.8-alpine      
    ports:
      - "9000:80"
    volumes:
      - ./nginx_conf.conf:/etc/nginx/conf.d/default.conf
    links:
      - node
    restart: always
    shm_size: '1gb'
    container_name: wcag_em_tool_nginx
