version: '2.2'

services:
    renderer:
      privileged: true
      build: ./renderer
      image: oawjs_renderer
      scale: 3
      cpus: 2
      restart: always
      command: node /opt/prerender/server.js
      
    proxy:
      build: ./proxy      
      image: oawjs_proxy
      command: node /opt/proxy/index.js
      restart: always
      ports:
        - "18088:18088"        
      container_name: oaw_proxy   

    nginx:
      image: nginx:1.13.8-alpine      
      volumes:
        - ./nginx/reverse.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/certs/server.crt:/etc/nginx/ssl/server.crt
        - ./nginx/certs/server.key:/etc/nginx/ssl/server.key        
      links:
        - renderer
      restart: always
      shm_size: '1gb'
      container_name: oaw_nginx
